CREATE TRIGGER actualiza_cant_actual AFTER INSERT OR DELETE ON nota FOR EACH ROW EXECUTE PROCEDURE cant_actual();

CREATE TRIGGER crea_constrasena AFTER INSERT ON estudiante FOR EACH ROW EXECUTE PROCEDURE crear_constrasena();

CREATE TRIGGER crear_usuario_profesor AFTER INSERT ON profesor FOR EACH ROW EXECUTE PROCEDURE crear_usuario_profesor();

CREATE TRIGGER tr1plan BEFORE INSERT ON plan FOR EACH ROW EXECUTE PROCEDURE f001plan();

CREATE TRIGGER tr1titulo BEFORE INSERT ON titulo FOR EACH ROW EXECUTE PROCEDURE f001titulo();
